Repository ovh-ux/ng-ovh-sso-auth, pull requests merged in 2019-07, with the labels that each got.

#16 feat(logout): add from with document referrer value on logout
  src/provider.js
Labels: feature

#17 Bugfix/minor improvements
  .editorconfig
  package.json
  yarn.lock
Labels: build

#18 Release v4.1.0
  .editorconfig
  package.json
  src/provider.js
  yarn.lock
Labels: release :package:
