Repository ovh-ux/ng-ovh-sso-auth, pull requests merged in 2019-08, with the labels that each got.

#21 feat(signup): manage incomplete nic at login
  src/constants.js
  src/provider.js
Labels: feature

#22 Release v4.2.0
  src/constants.js
  src/provider.js
Labels: release :package:

#28 Release v4.2.1
  src/provider.js
Labels: release :package:

#31 fix(signup): use browser language for redirection
  src/provider.js
Labels: bug
